# Generated by Django 4.1.3 on 2022-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='img',
            field=models.ImageField(default='', upload_to='workers/'),
        ),
    ]
